# Generated by Django 2.2.19 on 2022-09-06 09:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                    )),
            ],
            options={
                'verbose_name': 'Избранные рецепты',
                'verbose_name_plural': 'Избранные рецепты',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                    )),
                ('name', models.CharField(
                    max_length=200,
                    verbose_name='Название'
                    )),
                ('measurement_unit', models.CharField(
                    max_length=200,
                    verbose_name='Единица измерения'
                    )),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
            },
        ),
        migrations.CreateModel(
            name='IngredientAmount',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                    )),
                ('amount', models.IntegerField(
                    validators=[django.core.validators.MinValueValidator(1)],
                    verbose_name='Количество'
                    )),
            ],
            options={
                'verbose_name': 'Количество ингредиентов',
                'verbose_name_plural': 'Количество ингредиентов',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                    )),
                ('name', models.CharField(
                    max_length=200,
                    verbose_name='Название'
                    )),
                ('image', models.ImageField(
                    upload_to='recipes/images/',
                    verbose_name='Картинка'
                    )),
                ('text', models.TextField(verbose_name='Текст')),
                ('cooking_time', models.IntegerField(
                    validators=[django.core.validators.MinValueValidator(1)],
                    verbose_name='Время приготовления'
                    )),
                ('pub_date', models.DateTimeField(
                    auto_now_add=True,
                    db_index=True,
                    verbose_name='Дата публикации'
                    )),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                    )),
                ('name', models.CharField(
                    max_length=200,
                    unique=True,
                    verbose_name='Название'
                    )),
                ('color', models.CharField(
                    max_length=7,
                    unique=True,
                    verbose_name='Цвет в HEX'
                    )),
                ('slug', models.SlugField(
                    max_length=200,
                    unique=True,
                    verbose_name='Уникальный слаг'
                    )),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                    )),
                ('recipe', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='shopping_cart',
                    to='recipes.Recipe',
                    verbose_name='Рецепт'
                    )),
            ],
            options={
                'verbose_name': 'Список покупок',
                'verbose_name_plural': 'Списки покупок',
            },
        ),
    ]
